# Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

    
# Effort Controllers ---------------------------------------
lwr_0_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_0_joint
    pid: {p: 100, i: 0, d: 1}
lwr_1_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_1_joint
    pid: {p: 100, i: 0, d: 1}
lwr_2_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_2_joint
    pid: {p: 100, i: 0, d: 1}
lwr_3_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_3_joint
    pid: {p: 100, i: 0, d: 1}
lwr_4_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_4_joint
    pid: {p: 100, i: 0, d: 1}
lwr_5_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_5_joint
    pid: {p: 100, i: 0, d: 1}
lwr_6_joint:
    type: effort_controllers/JointEffortController
    joint: lwr_6_joint
    pid: {p: 100, i: 0, d: 1}
    

# Position Controllers ---------------------------------------
#~ lwr_0_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_0_joint
    #~ pid: {p: 21000.0, i: 10.0, d: 0.0}
#~ lwr_1_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_1_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_2_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_2_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_3_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_3_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_4_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_4_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_5_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_5_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_6_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_6_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
