# Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

    
# Position Controllers ---------------------------------------
lwr_0_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_0_joint
    pid: {p: 6000.0, i: 0.01, d: 1000.0}
lwr_1_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_1_joint
    pid: {p: 6000.0, i: 0.01, d: 1000.0}
lwr_2_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_2_joint
    pid: {p: 5000.0, i: 0.01, d: 300.0}
lwr_3_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_3_joint
    pid: {p: 5000.0, i: 0.01, d: 300.0}
lwr_4_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_4_joint
    pid: {p: 500.0, i: 0.01, d: 50.0}
lwr_5_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_5_joint
    pid: {p: 500.0, i: 0.01, d: 50.0}
lwr_6_joint:
    type: effort_controllers/JointPositionController
    joint: lwr_6_joint
    pid: {p: 100.0, i: 0.01, d: 20.0}
    

#~ # Position Controllers ---------------------------------------
#~ lwr_0_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_0_joint
    #~ pid: {p: 21000.0, i: 10.0, d: 0.0}
#~ lwr_1_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_1_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_2_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_2_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_3_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_3_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_4_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_4_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_5_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_5_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
#~ lwr_6_joint:
    #~ type: effort_controllers/JointPositionController
    #~ joint: lwr_6_joint
    #~ pid: {p: 50000.0, i: 10.0, d: 0.0}
